import Head from 'next/head'
import NavBar from '../components/frontend/Pages/NavBar.jsx'
import st1 from '../styles/themes/default.module.css'
import {MagnifyingGlassCircleIcon} from '@heroicons/react/24/outline'
import Footer from '../components/frontend/Pages/Footer.jsx'
import Category from '../components/frontend/Pages/Category'
import DropdownMenu from '../components/frontend/Pages/DropdownMenu'


export default function Home() {
  let themeClassName = st1
  return (
    <div className={themeClassName.homeMain_BG}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DropdownMenu theme={themeClassName} />
      <NavBar theme={themeClassName} />
      <h1 className={themeClassName.appName}>DDA</h1>
      <p className={themeClassName.appSubName}>Decentralized Digital Artstation</p>
      <p className={themeClassName.motto}>Buy and Sell 3d digital assets on the blockchain</p>
      <div className='rounded-full bg-white mx-auto flex justify-between my-5 w-11/12 sm:w-9/12 lg:w-8/12' >
      <input placeholder='Search by Product name, Category, Tags' type="search" name="" id="" className={themeClassName.inputSearch_header} />
      <MagnifyingGlassCircleIcon className={themeClassName.searchIcon} />
      </div>
      <Category theme={themeClassName} />

      <Footer theme={themeClassName} />
    </div>
  )
}
